owner: formspark
repo: status

sites:
  - name: formspark.io
    url: https://formspark.io
  - name: backend.formspark.io
    url: https://backend.formspark.io
  - name: dashboard.formspark.io
    url: https://dashboard.formspark.io
  - name: submitted.formspark.io
    url: https://submitted.formspark.io
  - name: documentation.formspark.io
    url: https://documentation.formspark.io

status-website:
  cname: status.formspark.io
  logoUrl: https://cdn.formspark.io/images/formspark/logos/formspark.svg
  name: Formspark
  navbar:
    - title: Status
      href: /
    - title: Formspark
      href: https://formspark.io
